name: "setup vcpkg"

branding:
  icon: 'package'
  color: 'blue'
description: Setup vcpkg binary in windows context
 
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@main
      with:
        repository: microsoft/vcpkg
    - shell: cmd
      run: bootstrap-vcpkg.bat
    - shell: pwsh
      run: setx VCPKG_ROOT "$pwd"
    - shell: pwsh
      name: set current console
      run: |
        $env:VCPKG_ROOT = "$pwd"
        $env:Path += ";$pwd"
     
      
